### ISSUE TITLE
Sekundes

### ISSUE THREAD

**Issue by MarkussPriede** [Alberts-Liepins/To-do#1]
Iestatot laiku nestrādā sekunžu lauciņš, bet tā strādā gan noņemšana, gan visas citas funkcijas.

EDIT:
Tas nav laika lauciņš, bet gan lauciņš, kur norāda PM vai AM. Firefoxā šī vieta nestrādāja, bet Chrome pārlūkā strādāja

**Comment by borderss** [comment]
Lapa tika testēta chrome, nezinu kādēļ tas nestrādātu citos pārlūkos, bet pārbaudīju programmu vairākas reizes un ar chrome un sekundes strādāja, paskatīšos vai ir iespējams kautko darīt..
